### ISSUE TITLE
Creating chainable functions and New Classes to calculate the Metrics

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/grimoirelab-manuscripts#62]
This issue proposes creating functions to segregate the metrics according to different fields, such as: `by_author`, `by_organizations` and `by_period` (weeks, months, years) which can be applied directly to metrics objects and the corresponding aggregations can be obtained.

These functions will make it easier for the user to do analysis on the basis of different users or orgs and to see the metrics evolve over periodic intervals.

They've been currently implemented in [this file](https://github.com/aswanipranjal/gsoc-manuscripts/blob/master/new_functions.py#L117) as a part of the Metric class.

We will also be creating new classes to calculate the metrics.

**Comment by jgbarah** [comment]
I like the approach. Maybe later we need specialized versions of these functions, such as for example when we have different records to consider in some specific case, or parameters for the functions. But for now, I guess we can try reimplementing with this, and we will already have a big win ;-)

We still need to comment how to integrate this in a giant pr with everything, or in separate ones, but I like it as a proof of concept.

Could you please write also some examples of use of these chainable methods, so that they are easier to understand to others?

**Comment by jgbarah** [comment]
Can we close this, @aswanipranjal?

**Comment by aswanipranjal** [comment]
Yeah, it's about time.
