### ISSUE TITLE
Porting manuscripts to use new functions and classes added in #67

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/grimoirelab-manuscripts#70]
I've tried to create more _chain-able_ functions/classes to be able to calculate the metrics. They are added as *manuscripts2* through #67.

This issue is about calculating the current metrics, that manuscripts produces, using these new functions/classes.
My approach will be to use the flow that is currently being used.

- Create classes for each of the data source
- Create sections of the report
- Calculate the metrics in each section using the above classes
- Generate the report.

In addition, this new report will mostly use Markdown instead of Latex.

**Comment by jgbarah** [comment]
This said, try to start small. Instead of submitting a PR with all the intended functionality, select just a few metrics, and produce the corresponding CSV. That would allow us to discuss changes in the architecture with easy: you won't need to change the code for a lot of metrics if we decide to make changes to the architecture.

**Comment by aswanipranjal** [comment]
By adding PRs #88  to  #104 (and all the PRs in between), the CSV files can now be generated using manuscripts2. I am closing this issue and creating a new one where the PDF generation can be discussed.
